//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherMashup.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Weather = new HashSet<Weather>();
        }
    
        public int LocationID { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string CityName { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<Weather> Weather { get; set; }
    }
}
